<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="6" total="11" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="139637" started-at="2018-02-26T14:02:44Z" finished-at="2018-02-26T14:05:04Z">
    <groups>
      <group name="MultipleRecords">
        <method signature="SmokeTest.testCaseWithMultipleRecords(java.lang.String, java.lang.String)[pri:-1, instance:com.framework.Package.tests.SmokeTest@307f6b8c]" name="testCaseWithMultipleRecords" class="com.framework.Package.tests.SmokeTest"/>
      </group> <!-- MultipleRecords -->
    </groups>
    <test name="Test" duration-ms="139637" started-at="2018-02-26T14:02:44Z" finished-at="2018-02-26T14:05:04Z">
      <class name="com.framework.Package.tests.SmokeTest">
        <test-method status="PASS" signature="ExtentReporting()[pri:0, instance:com.framework.Package.tests.SmokeTest@307f6b8c]" name="ExtentReporting" is-config="true" duration-ms="254" started-at="2018-02-26T19:32:44Z" finished-at="2018-02-26T19:32:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ExtentReporting -->
        <test-method status="PASS" signature="openBrowser(java.lang.String, java.lang.String)[pri:0, instance:com.framework.Package.tests.SmokeTest@307f6b8c]" name="openBrowser" is-config="true" duration-ms="7222" started-at="2018-02-26T19:32:44Z" finished-at="2018-02-26T19:32:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ie]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[STAGGING]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="FAIL" signature="testCaseWithMultipleRecords(java.lang.String, java.lang.String)[pri:-1, instance:com.framework.Package.tests.SmokeTest@307f6b8c]" name="testCaseWithMultipleRecords" duration-ms="10599" started-at="2018-02-26T19:32:51Z" data-provider="gettingDataUsingDataProvider" finished-at="2018-02-26T19:33:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[data1@em]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Pass1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Clearing username field Failed. Element is not visible or disabled on the webpage. By.name: userName]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Clearing username field Failed. Element is not visible or disabled on the webpage. By.name: userNameat com.framework.Package.driver.CommonMethods.clear(CommonMethods.java:87)at com.framework.Package.pageObjects.Login.passDataToUsernameField(Login.java:25)at com.framework.Package.tests.SmokeTest.testCaseWithMultipleRecords(SmokeTest.java:113)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseWithMultipleRecords -->
        <test-method status="FAIL" signature="testCaseWithMultipleRecords(java.lang.String, java.lang.String)[pri:-1, instance:com.framework.Package.tests.SmokeTest@307f6b8c]" name="testCaseWithMultipleRecords" duration-ms="30332" started-at="2018-02-26T19:33:02Z" data-provider="gettingDataUsingDataProvider" finished-at="2018-02-26T19:33:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[data2@em]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Pass2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Clearing username field Failed. Element is not visible or disabled on the webpage. By.name: userName]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Clearing username field Failed. Element is not visible or disabled on the webpage. By.name: userNameat com.framework.Package.driver.CommonMethods.clear(CommonMethods.java:87)at com.framework.Package.pageObjects.Login.passDataToUsernameField(Login.java:25)at com.framework.Package.tests.SmokeTest.testCaseWithMultipleRecords(SmokeTest.java:113)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseWithMultipleRecords -->
        <test-method status="FAIL" signature="testCaseWithMultipleRecords(java.lang.String, java.lang.String)[pri:-1, instance:com.framework.Package.tests.SmokeTest@307f6b8c]" name="testCaseWithMultipleRecords" duration-ms="30238" started-at="2018-02-26T19:33:32Z" data-provider="gettingDataUsingDataProvider" finished-at="2018-02-26T19:34:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[data3@em]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Pass3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Clearing username field Failed. Element is not visible or disabled on the webpage. By.name: userName]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Clearing username field Failed. Element is not visible or disabled on the webpage. By.name: userNameat com.framework.Package.driver.CommonMethods.clear(CommonMethods.java:87)at com.framework.Package.pageObjects.Login.passDataToUsernameField(Login.java:25)at com.framework.Package.tests.SmokeTest.testCaseWithMultipleRecords(SmokeTest.java:113)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseWithMultipleRecords -->
        <test-method status="FAIL" signature="testCaseWithMultipleRecords(java.lang.String, java.lang.String)[pri:-1, instance:com.framework.Package.tests.SmokeTest@307f6b8c]" name="testCaseWithMultipleRecords" duration-ms="30415" started-at="2018-02-26T19:34:03Z" data-provider="gettingDataUsingDataProvider" finished-at="2018-02-26T19:34:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[data4@em]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Pass4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Clearing username field Failed. Element is not visible or disabled on the webpage. By.name: userName]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Clearing username field Failed. Element is not visible or disabled on the webpage. By.name: userNameat com.framework.Package.driver.CommonMethods.clear(CommonMethods.java:87)at com.framework.Package.pageObjects.Login.passDataToUsernameField(Login.java:25)at com.framework.Package.tests.SmokeTest.testCaseWithMultipleRecords(SmokeTest.java:113)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseWithMultipleRecords -->
        <test-method status="FAIL" signature="testCaseWithMultipleRecords(java.lang.String, java.lang.String)[pri:-1, instance:com.framework.Package.tests.SmokeTest@307f6b8c]" name="testCaseWithMultipleRecords" duration-ms="30315" started-at="2018-02-26T19:34:33Z" data-provider="gettingDataUsingDataProvider" finished-at="2018-02-26T19:35:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[data5@em]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Pass5]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Clearing username field Failed. Element is not visible or disabled on the webpage. By.name: userName]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Clearing username field Failed. Element is not visible or disabled on the webpage. By.name: userNameat com.framework.Package.driver.CommonMethods.clear(CommonMethods.java:87)at com.framework.Package.pageObjects.Login.passDataToUsernameField(Login.java:25)at com.framework.Package.tests.SmokeTest.testCaseWithMultipleRecords(SmokeTest.java:113)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseWithMultipleRecords -->
        <test-method status="PASS" signature="end()[pri:0, instance:com.framework.Package.tests.SmokeTest@307f6b8c]" name="end" is-config="true" duration-ms="475" started-at="2018-02-26T19:35:03Z" finished-at="2018-02-26T19:35:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- com.framework.Package.tests.SmokeTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
